
variables:
  imageName: 'k8sdemo-docker-image'
  
steps:
- task: Npm@1
  displayName: 'Insatall NPM package'
  inputs:
    command: 'install'
    workingDir: './app'

- task: PowerShell@2
  displayName: Terrafom Init
  inputs:
    targetType: 'inline'
    script: |
      # run terrafom 
      terraform init
    workingDirectory: './infra/dev'

- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
        repository: $(imageName)
        dockerfile: app/Dockerfile
        command: buildAndPush
        containerRegistry: $(dockerRegistryServiceConnection)