stages:
- stage: SteupInfrastracture
  displayName: Previsioning Kubernetes Cluster
  jobs:
  - job: 
    steps:
    - task: PowerShell@2
      displayName: Terrafom Init
      inputs:
        targetType: 'inline'
        script: |
          # run terrafom 
          terraform init
        workingDirectory: '.\infra\dev'
