stages:
- stage: SteupInfrastracture
  displayName: Previsioning Kubernetes Cluster
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@0
      displayName: Init Terraform
      inputs:
        terraformVersion: '0.12.3'


