
variables:
  imageName: 'k8s-demo'
  
steps:
  - task: Docker@2
    displayName: Build and Push an image
    inputs:
          containerRegistry: 'dockerctr'
          repository: $(imageName)
          command: buildAndPush
          Dockerfile: app/Dockerfile
          tags: 1.0
      
  - task: PowerShell@2
    displayName: Terrafom Init & apply
    inputs:
      targetType: 'inline'
      script: |
        # run terrafom 
        terraform init
        terraform apply -auto-approve
      workingDirectory: './infra/k8s-cluster'


