
variables:
  imageName: 'k8sdemo-docker-image'
  
steps:
- task: Npm@1
  displayName: 'Insatall NPM package'
  inputs:
    command: 'install'
    workingDir: './app/package.json'

- task: PowerShell@2
  displayName: Terrafom Init
  inputs:
    targetType: 'inline'
    script: |
      # run terrafom 
      terraform init
    workingDirectory: './infra/dev'

- task: Docker@2
  displayName: Build an image
  inputs:
        repository: $(imageName)
        command: build
        Dockerfile: app/Dockerfile