
variables:
  imageName: 'dockerctr.azurecr.io/k8s-demo:1.0'
  
steps:
  - task: Docker@2
    displayName: Build an image
    inputs:
          repository: $(imageName)
          command: build
          Dockerfile: app/Dockerfile

  - task: PowerShell@2
    displayName: Terrafom Init
    inputs:
      targetType: 'inline'
      script: |
        # run terrafom 
        terraform init
      workingDirectory: '/infra/k8s-cluster'